# https://alacritty.org/config-alacritty.html

shell = "/opt/homebrew/bin/fish"

[window]
padding = { x = 10, y = 8 }
dynamic_padding = true

[font]
normal = { family = "JetBrains Mono", style = "ExtraLight" }
size = 14

# https://github.com/alebelcor/alacritty-snazzy/blob/master/snazzy.yml

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#eff0eb"
background = "#282a36"

[colors.cursor]
cursor = "#97979b"

[colors.selection]
text = "#282a36"
background = "#feffff"

[colors.normal]
black = "#282a36"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#f1f1f0"

[colors.bright]
black = "#686868"
red = "#ff5c57"
green = "#5af78e"
yellow = "#f3f99d"
blue = "#57c7ff"
magenta = "#ff6ac1"
cyan = "#9aedfe"
white = "#eff0eb"

[cursor]
style = { shape = "block", blinking = "always" }
blink_interval = 500
