# https://taskfile.dev

version: '3'

silent: true

dotenv:
  - .env

tasks:
  create-symlink-safe:
    internal: true
    cmds:
      - '{{.USER_WORKING_DIR}}/scripts/symlink-safe.sh "{{.SOURCE}}" "{{.TARGET}}"'

  default:
    desc: List all available tasks
    cmds:
      - task --list-all

  1password-ssh:
    desc: Setup 1password SSH agent
    cmds:
      - mkdir -p {{.HOME}}/.1password
      - ln -sf {{.HOME}}/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock {{.HOME}}/.1password/agent.sock

  agents:
    desc: Setup AI agents
    env:
      DISABLE_TELEMETRY: 1
    cmds:
      # Local skills
      - mkdir -p {{.HOME}}/.agents/skills
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/agents/skills/git/commit-message'
          TARGET: '{{.HOME}}/.agents/skills/git-commit-message'
      # https://github.com/ast-grep/agent-skill
      - bunx skills add ast-grep/agent-skill --agent claude-code --global --yes
      # https://github.com/anthropics/skills
      - bunx skills add anthropics/skills --skill frontend-design --agent claude-code --global --yes
      # https://github.com/blader/humanizer
      - bunx skills add blader/humanizer --agent claude-code --global --yes
      # https://github.com/planetscale/database-skills
      - bunx skills add planetscale/database-skills --skill mysql --skill postgres --agent claude-code --global --yes
      # https://github.com/stripe/ai
      # - bunx skills add stripe/ai --skill stripe-best-practices --agent claude-code --global --yes
      # https://github.com/vercel-labs/agent-browser
      - bunx skills add vercel-labs/agent-browser --agent claude-code --global --yes
      # https://github.com/vercel-labs/agent-skills
      - bunx skills add vercel-labs/agent-skills --skill vercel-react-best-practices --agent claude-code --global --yes
      # https://github.com/mike182uk/agent-skills
      - bunx skills add mike182uk/agent-skills --agent claude-code --global --yes

  brew-bundle:
    desc: Update brewfile with installed formulae / casks
    preconditions:
      - command -v brew
      - command -v jq
      - "[ -f {{.HOME}}/.cursor/extensions/extensions.json ] && exit 0 || exit 1"
    cmds:
      - brew bundle dump --no-vscode --force --describe --file {{.USER_WORKING_DIR}}/config/homebrew/Brewfile
      # Manually append vscode extensions based on what extensions have been added to Cursor
      - jq -r '.[].identifier.id' {{.HOME}}/.cursor/extensions/extensions.json | sort -u | while read -r id; do echo "vscode \"$id\"" >> {{.USER_WORKING_DIR}}/config/homebrew/Brewfile; done

  brew-install:
    desc: Install formulae / casks listed in Brewfile
    preconditions:
      - command -v brew
    cmds:
      - brew bundle --file {{.USER_WORKING_DIR}}/config/homebrew/Brewfile

  bun:
    desc: Setup Bun config
    cmds:
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/bun/bunfig.toml'
          TARGET: '{{.HOME}}/.bunfig.toml'
      - bun install -g agent-browser
      - bunx playwright install

  claude:
    desc: Setup Claude code
    preconditions:
      - command -v npm
    cmds:
      # Settings
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/claude/settings.json'
          TARGET: '{{.HOME}}/.claude/settings.json'
      # Statusline
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/claude/statusline.sh'
          TARGET: '{{.HOME}}/.claude/statusline.sh'
      # Agents config
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/agents/AGENTS.md'
          TARGET: '{{.HOME}}/CLAUDE.md'
      # Local skills
      - mkdir -p {{.HOME}}/.claude/skills
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.HOME}}/.agents/skills/git-commit-message'
          TARGET: '{{.HOME}}/.claude/skills/git-commit-message'
      # Install
      - curl -fsSL http://claude.ai/install.sh | bash
      # MCP
      - claude mcp add --scope user --transport http context7 https://mcp.context7.com/mcp
      - claude mcp add --scope user playwright npx @playwright/mcp@latest
      - claude mcp add --scope user chrome-devtools npx chrome-devtools-mcp@latest
      - claude mcp add --scope user --transport http sentry https://mcp.sentry.dev/mcp
      - claude mcp add --scope user --transport http linear https://mcp.linear.app/mcp
      - claude mcp add --scope user --transport http grep https://mcp.grep.app

  codex:
    desc: Setup Codex config
    cmds:
      - mkdir -p {{.HOME}}/.codex
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/agents/AGENTS.md'
          TARGET: '{{.HOME}}/.codex/AGENTS.md'

  cursor:
    desc: Setup Cursor config
    vars:
      CURSOR_CFG_PATH: '{{.HOME}}/Library/Application Support/Cursor/User'
    cmds:
      - mkdir -p '{{.CURSOR_CFG_PATH}}'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/cursor/settings.json'
          TARGET: '{{.CURSOR_CFG_PATH}}/settings.json'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/cursor/keybindings.json'
          TARGET: '{{.CURSOR_CFG_PATH}}/keybindings.json'

  editorconfig:
    desc: Setup editorconfig config
    cmds:
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/editorconfig/editorconfig'
          TARGET: '{{.HOME}}/.editorconfig'

  fish:
    desc: Setup ðŸŸ config
    cmds:
      - mkdir -p {{.HOME}}/.config
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/fish'
          TARGET: '{{.HOME}}/.config/fish'
      - '[ -f {{.HOME}}/.config/fish/config.local.fish ] || touch {{.HOME}}/.config/fish/config.local.fish'

  fish-completions:
    desc: Install fish completions for installed programs
    preconditions:
      - command -v orbctl
      - command -v task
      - command -v ast-grep
    cmds:
      - orbctl completion fish > {{.HOME}}/.config/fish/completions/orbstack.fish
      - task --completion fish > {{.HOME}}/.config/fish/completions/task.fish
      - ast-grep completions fish > {{.HOME}}/.config/fish/completions/ast-grep.fish

  fish-init:
    desc: Install fisher and plugins
    preconditions:
      - command -v fish
    cmds:
      # Install fisher
      - fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'
      # Install plugins
      - fish -c 'fisher update'

  ghostty:
    desc: Install Ghostty config
    cmds:
      - mkdir -p {{.HOME}}/.config/ghostty
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/ghostty/config'
          TARGET: '{{.HOME}}/.config/ghostty/config'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/ghostty/themes'
          TARGET: '{{.HOME}}/.config/ghostty/themes'

  git:
    desc: Setup Git config
    preconditions:
      - command -v git
    cmds:
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/git/gitattributes'
          TARGET: '{{.HOME}}/.gitattributes'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/git/gitignore'
          TARGET: '{{.HOME}}/.gitignore'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/git/gitconfig.local'
          TARGET: '{{.HOME}}/.gitconfig.local'
      - git config --global include.path ~/.gitconfig.local
      - '[[ -n "$GIT_USERNAME" ]] && git config --global user.name "$GIT_USERNAME"; true'
      - '[[ -n "$GIT_EMAIL" ]] && git config --global user.email "$GIT_EMAIL"; true'

  git-gpg:
    desc: Setup Git GPG commit signing
    vars:
      GPG_SSH_PROGRAM: /Applications/1Password.app/Contents/MacOS/op-ssh-sign
    preconditions:
      - command -v git
    cmds:
      - git config --global commit.gpgsign true
      - git config --global gpg.format ssh
      - '[ -f "{{.GPG_SSH_PROGRAM}}" ] && git config --global gpg.ssh.program "{{.GPG_SSH_PROGRAM}}"'
      - '[[ -n "$GIT_SIGNING_KEY" ]] && git config --global user.signingkey "$GIT_SIGNING_KEY"; true'

  mise:
    desc: Setup mise config
    preconditions:
      - command -v mise
    cmds:
      - mkdir -p {{.HOME}}/.config/mise
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/mise/config.toml'
          TARGET: '{{.HOME}}/.config/mise/config.toml'
      - mise install

  macos:
    desc: Configure macOS
    cmds:
      - '{{.USER_WORKING_DIR}}/scripts/setup-macos.sh'

  raycast:
    desc: Install Raycast preferences
    cmds:
      - mkdir -p {{.HOME}}/.config/raycast
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/raycast/script-commands'
          TARGET: '{{.HOME}}/.config/raycast/script-commands'

  opencode:
    desc: Setup OpenCode config
    cmds:
      - mkdir -p {{.HOME}}/.config/opencode
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/opencode/opencode.jsonc'
          TARGET: '{{.HOME}}/.config/opencode/opencode.jsonc'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/agents/AGENTS.md'
          TARGET: '{{.HOME}}/.config/opencode/AGENTS.md'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/opencode/commands'
          TARGET: '{{.HOME}}/.config/opencode/commands'

  ssh:
    desc: Setup SSH config
    deps:
      - 1password-ssh
    cmds:
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/ssh/config'
          TARGET: '{{.HOME}}/.ssh/config'

  starship:
    desc: Setup starship config
    cmds:
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/starship/starship.toml'
          TARGET: '{{.HOME}}/.config/starship.toml'

  sublime-text:
    desc: Setup Sublime Text config
    vars:
      ST_CFG_PATH: '{{.HOME}}/Library/Application Support/Sublime Text/Packages/User'
      ST_PKG_PATH: '{{.HOME}}/Library/Application Support/Sublime Text/Installed Packages'
    cmds:
      - mkdir -p '{{.ST_CFG_PATH}}'
      - mkdir -p '{{.ST_PKG_PATH}}'
      # https://packagecontrol.io/installation
      - '[ -f "{{.ST_PKG_PATH}}/Package Control.sublime-package" ] || curl -sL -o "{{.ST_PKG_PATH}}/Package Control.sublime-package" "https://packagecontrol.io/Package%20Control.sublime-package"'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/sublime-text/Preferences.sublime-settings'
          TARGET: '{{.ST_CFG_PATH}}/Preferences.sublime-settings'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/sublime-text/Package Control.sublime-settings'
          TARGET: '{{.ST_CFG_PATH}}/Package Control.sublime-settings'

  tmux:
    desc: Setup tmux config
    cmds:
      - '[ -d "{{.HOME}}/.tmux/plugins/tpm" ] || git clone https://github.com/tmux-plugins/tpm {{.HOME}}/.tmux/plugins/tpm'
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/tmux/tmux.conf'
          TARGET: '{{.HOME}}/.tmux.conf'
      - |
        if [[ -n "$IPINFO_API_TOKEN" ]]; then
          if ! grep -q "IPINFO_API_TOKEN" {{.HOME}}/.config/fish/config.local.fish; then
            echo "" >> {{.HOME}}/.config/fish/config.local.fish
            echo "# Init IPINFO_API_TOKEN" >> {{.HOME}}/.config/fish/config.local.fish
            echo "" >> {{.HOME}}/.config/fish/config.local.fish
            echo "set --global --export IPINFO_API_TOKEN $IPINFO_API_TOKEN" >> {{.HOME}}/.config/fish/config.local.fish
          fi
        fi
      - "{{.HOME}}/.tmux/plugins/tpm/bin/install_plugins"

  zed:
    desc: Setup Zed config
    cmds:
      - mkdir -p {{.HOME}}/.config/zed
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/zed/settings.json'
          TARGET: '{{.HOME}}/.config/zed/settings.json'

  zsh:
    desc: Setup zsh config
    cmds:
      - task: create-symlink-safe
        vars:
          SOURCE: '{{.USER_WORKING_DIR}}/config/zsh/zprofile'
          TARGET: '{{.HOME}}/.zprofile'
