# Init homebrew

for brew_path in /opt/homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin/brew; do
	if [ -x "$brew_path" ]; then
		eval "$("$brew_path" shellenv)"
		break
	fi
done

# Init editor

if command -v zed > /dev/null; then
	export EDITOR='zed --wait'
elif command -v nvim > /dev/null; then
	export EDITOR='nvim'
else
	export EDITOR='vim'
fi
