# https://herdr.dev/docs/configuration/
# https://herdr.dev/docs/config-reference/

onboarding = false

[theme]
auto_switch = false
name = "tokyo-night"

[keys]
reload_config = "prefix+r"
resize_mode = "prefix+shift+r"
split_vertical = "prefix+|"
split_horizontal = "prefix+_"

[[keys.command]]
key = "prefix+ctrl+d"
type = "pane"
command = "revdiff"

[ui.sound]
enabled = false

[ui]
agent_panel_sort = "spaces"
prompt_new_tab_name = false

[ui.sidebar.spaces]
row_gap = 1

[ui.sidebar.agents]
row_gap = 1
