[settings]
legacy_version_file = true
idiomatic_version_file_enable_tools = ["node", "terraform", "yarn", "rust"]

[tools]
actionlint = "latest"
bun = "latest"
deno = "latest"
go = "latest"
node = "24"
nub = "latest"
opencode = "latest"
